version: '3.8'
services:
 dev-db:
  image: postgres:13
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: password
   POSTGRES_DB: bookmarks
  networks:
    - bookmarks
 test-db:
  image: postgres:13
  ports:
   - "5433:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: password
   POSTGRES_DB: bookmarks
  networks:
    - bookmarks
networks:
  bookmarks: